version: '3'
services:
    rasa:
      user: root
      build: 
        context: ./rasa/lernen-cloud-de
      volumes:
      - "./rasa/lernen-cloud-de:/app"
      ports: 
        - "12345:5005"
        # Server Port: 12345:5005
        # Local Port: 5005:5005
